{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: forge-gateway
  labels:
    {{- include "forge-gateway.labels" . | nindent 4 }}
    release: monitoring # kube-prometheus-stack's selector
spec:
  selector:
    matchLabels:
      {{- include "forge-gateway.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.serviceMonitor.interval }}
{{- end }}
