apiVersion: v1
kind: Service
metadata:
  name: forge-gateway
  labels:
    {{- include "forge-gateway.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "forge-gateway.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
